import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import Services from '@/components/Services'
import Form from '@/components/Form'
import Carousel from '@/components/Carousel'
import Why from '@/components/Why'




export default function Home() {
  return (
    <>
      <Head>
        <title>Grindcrete</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />

        <Services />
        <Form />
        <Why />
      </main>
    </>
  )
}
